// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIq8d1qzAUv8LZXLkA4W2Gdu6glt0ESKw',
    appId: '1:737339495290:web:8eb1a5e06605eb8c1f3cc3',
    messagingSenderId: '737339495290',
    projectId: 'fir-series-8fb73',
    authDomain: 'fir-series-8fb73.firebaseapp.com',
    storageBucket: 'fir-series-8fb73.firebasestorage.app',
    measurementId: 'G-WE6ZG2Q7HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChg9zDdXyrZMfokZqpX30Yv8TwPkV6BBI',
    appId: '1:737339495290:android:d506189f0807bf4f1f3cc3',
    messagingSenderId: '737339495290',
    projectId: 'fir-series-8fb73',
    storageBucket: 'fir-series-8fb73.firebasestorage.app',
  );
}
